[project]
name = "tutorial"
version = "0.1.0"
description = "Tipi Tutorial"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "tensorimgpipeline[tensorboard]==1.2.2",
  "torch>=2.9.1",
  "torchvision>=0.24.1",
]

[tool.uv]
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = ["mkdocstrings[python]>=1.0.4", "zensical>=0.0.39"]
